server:
  port: 80
  servlet:
    context-path: /

myEmail: ming15179@foxmail.com

spring:
  datasource:
#    使用druid数据源，可访问 http://localhost/druid 进入druid后台管理系统
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myBlog?useSSl=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true

    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # DruidFilterConfiguration
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
#        只允许本机访问
        allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.46.121
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: 1
        # 登录密码
        login-password: 1


  mail:
#    QQ邮箱
    username: QQ邮箱地址
#    qq邮箱授权码
    password:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: utf-8

  thymeleaf:
    cache: false
#    上传文件最大值
  servlet:
    multipart:
      max-file-size: 20971520

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    #    启用驼峰支持
#    map-underscore-to-camel-case: true




pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

logging:  #日志级别
  level:
    root: info
    com.blog: info
#    启用日志文件记录
  file:
    name: log/blog.log
